USE [master]
GO

/****** Object:  Database [FinalProject]    Script Date: 4/22/2020 6:45:59 PM ******/
CREATE DATABASE [FinalProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FinalProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FinalProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FinalProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FinalProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FinalProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FinalProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FinalProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FinalProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FinalProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FinalProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [FinalProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FinalProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FinalProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FinalProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FinalProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FinalProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FinalProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FinalProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FinalProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FinalProject] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FinalProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FinalProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FinalProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FinalProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FinalProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FinalProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FinalProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FinalProject] SET RECOVERY FULL 
GO

ALTER DATABASE [FinalProject] SET  MULTI_USER 
GO

ALTER DATABASE [FinalProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FinalProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FinalProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FinalProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FinalProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FinalProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FinalProject] SET  READ_WRITE 
GO


